spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:mariadb://np.imchobo.com:3306/alba  # DB 접속 주소 (log4jdbc로 감싼 형태)
      username: sample                # DB 사용자명
      password: 1234                  # DB 비밀번호
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy  # log4jdbc 드라이버
